"""mod Add columns Venta

Revision ID: 2c7bdcf0b0b9
Revises: 7b96844d8aa5
Create Date: 2023-08-30 19:07:01.755787

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c7bdcf0b0b9'
down_revision = '7b96844d8aa5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('venta', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ven_comment', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('ven_acuenta', sa.Numeric(precision=10, scale=2), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('venta', schema=None) as batch_op:
        batch_op.drop_column('ven_acuenta')
        batch_op.drop_column('ven_comment')

    # ### end Alembic commands ###
