"""Add column Venta cancelacion

Revision ID: 9782a65af223
Revises: 2c7bdcf0b0b9
Create Date: 2023-09-08 15:28:00.217085

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9782a65af223'
down_revision = '2c7bdcf0b0b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('venta', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ven_date_cancelacion', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('venta', schema=None) as batch_op:
        batch_op.drop_column('ven_date_cancelacion')

    # ### end Alembic commands ###
